sudo: required

env:
  global:
    - DOCKER_VERSION=1.9.1  # Install Docker version 1.9.1

services:
  - docker

script:
  - docker build -t zokeber/redis:latest .
  - docker run -d -p 6379:6379 --name redis zokeber/redis:latest
  - docker ps -a
